name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Storybook build
        run: npm run build-storybook

      - name: Build the Nuxt.js application
        run: npm run build

      - name: Run tests (if applicable)
        run: npm run test || echo "No tests defined"

      # Optional: Deploy the application
      # Uncomment and adjust this step according to your deployment strategy
      # - name: Deploy to production
      #   run: npm run deploy # Adjust based on your deployment command
